package utils

import (
	"time"
)

var MockUsers = []User{
	{
		ID:               "1asda433sdaasd2",
		Name:             "Jakov K",
		Email:            "knezevic.jakov@gmail.com",
		AccountCreatedAt: IntToString(time.Now().UnixMilli()),
		Image:            "https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcQdAnprsidzbOSZ4jI1SvcFeIEuFKwBLrILGo8tLCEA4ixMzfxUQfk6onBDhipea4sD",
	},
	{
		ID:               "2bvcv565vbbvc3a",
		Name:             "Patrick Jane",
		Email:            "pjane@mail.com",
		AccountCreatedAt: IntToString(time.Now().UnixMilli()),
		Image:            "https://media.wired.com/photos/593261cab8eb31692072f129/master/w_2560%2Cc_limit/85120553.jpg",
	},
	{
		ID:               "3zdfzdf34adadsa",
		Name:             "Kimball Cho",
		Email:            "kcho@mail.com",
		AccountCreatedAt: IntToString(time.Now().UnixMilli()),
		Image:            "https://cdn.britannica.com/89/149189-050-68D7613E/Bengal-tiger.jpg",
	},
}

var MockProducts = []Product{
	{
		ID:               1,
		Title:            "Brown Brim",
		ShortDescription: "The brim hat is a classic and versatile accessory that seamlessly marries fashion and practicality",
		Description:      "The brim hat is a classic and versatile accessory that seamlessly marries fashion and practicality. Brim hats come in a variety of styles, materials, and colors, catering to a range of fashion preferences. From classic straw or woven designs for a breezy summer look to wool or felt options that offer warmth and elegance during cooler seasons, there's a brim hat for every occasion. The color palette spans from neutral tones to vibrant hues, allowing you to express your personal style. Crafted with quality and durability in mind, the brim hat promises long-lasting wear and timeless style. Its ability to combine fashion-forward design with practical sun protection or weather resistance ensures it remains a reliable accessory for those who appreciate both form and function. Whether you're seeking a touch of elegance, sun protection, or an instant style upgrade, the brim hat stands as a versatile and iconic addition to your accessory collection. It encapsulates the essence of classic fashion while adapting to modern trends and needs, making it a beloved choice for individuals with a keen sense of style.",
		Image:            "https://i.ibb.co/ZYW3VTp/brown-brim.png",
		Price:            13.99,
		DateAdded:        "1682267143000",
		Category:         "unisex",
		Subcategory:      "hats",
		Rating: ProductRating{
			Rate:  3.9,
			Count: 120,
		},
	},
	{
		ID:               2,
		Price:            9.99,
		Title:            "Blue Beanie",
		ShortDescription: "Suitable for various seasons, from winter to transitional weather, and even cool summer nights",
		Description:      "The beanie hat is a timeless and versatile accessory that effortlessly combines comfort and style. This snug-fitting, knitted headwear piece is designed to keep you warm while adding a touch of casual sophistication to your ensemble. Beanie hats are known for their simplicity, featuring a snug, close-fitting design that hugs the contours of your head, providing excellent insulation and protection against chilly weather. Crafted from a variety of materials such as soft wool, cozy acrylic, or breathable cotton, beanies are suitable for various seasons, from winter to transitional weather, and even cool summer nights. One of the beanie's defining characteristics is its versatility. Available in an array of colors and patterns, you can easily find the perfect beanie to match your personal style and mood. Whether you opt for a classic solid color, a trendy striped design, or a playful pom-pom embellishment, there's a beanie to suit every fashion preference.",
		Image:            "https://i.ibb.co/ypkgK0X/blue-beanie.png",
		DateAdded:        "1695036343000",
		Category:         "unisex",
		Subcategory:      "hats",
		Rating: ProductRating{
			Rate:  3.3,
			Count: 203,
		},
	},
	{
		ID:               3,
		Title:            "Brown Cowboy",
		ShortDescription: "Crafted from durable materials such as felt, straw, or leather, the cowboy hat is designed to withstand the harshest elements of the outdoors",
		Description:      "Crafted from durable materials such as felt, straw, or leather, the cowboy hat is designed to withstand the harshest elements of the outdoors. Its wide brim provides ample shade from the scorching sun, shielding the wearer's face and neck, while the crown offers ventilation and protection from rain and wind. Beyond its functionality, the cowboy hat has become an enduring fashion statement. Available in a wide range of colors and materials, it allows wearers to express their unique personality and style. Whether you prefer a classic brown or black hat for a timeless Western look, or a vibrant and intricate design for a bold fashion statement, there's a cowboy hat to suit every taste. The cowboy hat is not just an accessory; it's a symbol of the American frontier spirit, adventure, and a connection to the great outdoors. Whether worn by cowboys and cowgirls on the ranch, country music stars on stage, or anyone looking to add a touch of Western flair to their wardrobe, the cowboy hat remains a true icon of American culture and heritage.",
		Image:            "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
		Price:            12.99,
		DateAdded:        "1682267143000",
		Category:         "unisex",
		Subcategory:      "hats",
		Rating: ProductRating{
			Rate:  3.9,
			Count: 120,
		},
	},
	{
		ID:               4,
		Image:            "https://i.ibb.co/RjBLWxB/grey-brim.png",
		Title:            "Grey Brim",
		ShortDescription: "Crafted with quality and durability in mind, the brim hat promises long-lasting wear and timeless style",
		Description:      "The brim hat is a classic and versatile accessory that seamlessly marries fashion and practicality. Brim hats come in a variety of styles, materials, and colors, catering to a range of fashion preferences. From classic straw or woven designs for a breezy summer look to wool or felt options that offer warmth and elegance during cooler seasons, there's a brim hat for every occasion. The color palette spans from neutral tones to vibrant hues, allowing you to express your personal style. Crafted with quality and durability in mind, the brim hat promises long-lasting wear and timeless style. Its ability to combine fashion-forward design with practical sun protection or weather resistance ensures it remains a reliable accessory for those who appreciate both form and function. Whether you're seeking a touch of elegance, sun protection, or an instant style upgrade, the brim hat stands as a versatile and iconic addition to your accessory collection. It encapsulates the essence of classic fashion while adapting to modern trends and needs, making it a beloved choice for individuals with a keen sense of style.",
		Price:            10.99,
		DateAdded:        "1695036343000",
		Category:         "unisex",
		Subcategory:      "hats",
		Rating: ProductRating{
			Rate:  4.8,
			Count: 400,
		},
	},
	{
		ID:               5,
		Image:            "https://i.ibb.co/YTjW3vF/green-beanie.png",
		Title:            "Green Beanie",
		ShortDescription: "Available in an array of colors and patterns, you can easily find the perfect beanie to match your personal style and mood",
		Description:      "The beanie hat is a timeless and versatile accessory that effortlessly combines comfort and style. This snug-fitting, knitted headwear piece is designed to keep you warm while adding a touch of casual sophistication to your ensemble. Beanie hats are known for their simplicity, featuring a snug, close-fitting design that hugs the contours of your head, providing excellent insulation and protection against chilly weather. Crafted from a variety of materials such as soft wool, cozy acrylic, or breathable cotton, beanies are suitable for various seasons, from winter to transitional weather, and even cool summer nights. One of the beanie's defining characteristics is its versatility. Available in an array of colors and patterns, you can easily find the perfect beanie to match your personal style and mood. Whether you opt for a classic solid color, a trendy striped design, or a playful pom-pom embellishment, there's a beanie to suit every fashion preference.",
		Price:            9.99,
		DateAdded:        "1682267143000",
		Category:         "unisex",
		Subcategory:      "hats",
		Rating: ProductRating{
			Rate:  2.9,
			Count: 340,
		},
	},
	{
		ID:               6,
		Image:            "https://i.ibb.co/rKBDvJX/palm-tree-cap.png",
		Price:            8.99,
		Title:            "Palm Tree Cap",
		ShortDescription: "They're perfect for those \"bad hair days,\" as they provide a quick and stylish solution to keep you looking put together",
		Description:      "Sporty and casual headwear accessory that effortlessly combines comfort, versatility, and style. Known for its iconic design, it's a wardrobe staple that transcends generations and trends. Caps come in a wide variety of materials, with cotton, canvas, and polyester being common choices. This diversity in materials allows you to select a cap that suits your specific needs, whether you're looking for breathability in hot weather, moisture-wicking properties for physical activity, or warmth in cooler climates. Known for their accessibility and ease of wear. They're perfect for those \"bad hair days,\" as they provide a quick and stylish solution to keep you looking put together. Moreover, caps are suitable for various occasions, from laid-back weekends to active outdoor adventures to casual outings with friends.",
		DateAdded:        "1682267143000",
		Category:         "unisex",
		Subcategory:      "hats",
		Rating: ProductRating{
			Rate:  2.9,
			Count: 250,
		},
	},
	{
		ID:               7,
		Image:            "https://i.ibb.co/bLB646Z/red-beanie.png",
		Price:            9.99,
		Title:            "Red Beanie",
		ShortDescription: "Crafted from a variety of materials such as soft wool, cozy acrylic, or breathable cotton",
		Description:      "The beanie hat is a timeless and versatile accessory that effortlessly combines comfort and style. This snug-fitting, knitted headwear piece is designed to keep you warm while adding a touch of casual sophistication to your ensemble. Beanie hats are known for their simplicity, featuring a snug, close-fitting design that hugs the contours of your head, providing excellent insulation and protection against chilly weather. Crafted from a variety of materials such as soft wool, cozy acrylic, or breathable cotton, beanies are suitable for various seasons, from winter to transitional weather, and even cool summer nights. One of the beanie's defining characteristics is its versatility. Available in an array of colors and patterns, you can easily find the perfect beanie to match your personal style and mood. Whether you opt for a classic solid color, a trendy striped design, or a playful pom-pom embellishment, there's a beanie to suit every fashion preference.",
		DateAdded:        "1691220343000",
		Category:         "unisex",
		Subcategory:      "hats",
		Rating: ProductRating{
			Rate:  4.8,
			Count: 400,
		},
	},
	{
		ID:               8,
		Image:            "https://i.ibb.co/1f2nWMM/wolf-cap.png",
		Title:            "Wolf Cap",
		ShortDescription: "Known for its iconic design, it's a wardrobe staple that transcends generations and trends",
		Description:      "Sporty and casual headwear accessory that effortlessly combines comfort, versatility, and style. Known for its iconic design, it's a wardrobe staple that transcends generations and trends. Caps come in a wide variety of materials, with cotton, canvas, and polyester being common choices. This diversity in materials allows you to select a cap that suits your specific needs, whether you're looking for breathability in hot weather, moisture-wicking properties for physical activity, or warmth in cooler climates. Known for their accessibility and ease of wear. They're perfect for those \"bad hair days,\" as they provide a quick and stylish solution to keep you looking put together. Moreover, caps are suitable for various occasions, from laid-back weekends to active outdoor adventures to casual outings with friends.",
		Price:            9.99,
		DateAdded:        "1695036343000",
		Category:         "unisex",
		Subcategory:      "hats",
		Rating: ProductRating{
			Rate:  3.9,
			Count: 120,
		},
	},
	{
		ID:               9,
		Title:            "Blue Snapback",
		ShortDescription: "Sporty and casual headwear accessory that effortlessly combines comfort, versatility, and style",
		Description:      "Sporty and casual headwear accessory that effortlessly combines comfort, versatility, and style. Known for its iconic design, it's a wardrobe staple that transcends generations and trends. Caps come in a wide variety of materials, with cotton, canvas, and polyester being common choices. This diversity in materials allows you to select a cap that suits your specific needs, whether you're looking for breathability in hot weather, moisture-wicking properties for physical activity, or warmth in cooler climates. Known for their accessibility and ease of wear. They're perfect for those \"bad hair days,\" as they provide a quick and stylish solution to keep you looking put together. Moreover, caps are suitable for various occasions, from laid-back weekends to active outdoor adventures to casual outings with friends.",
		Image:            "https://i.ibb.co/X2VJP2W/blue-snapback.png",
		Price:            8.99,
		DateAdded:        "1691220343000",
		Category:         "unisex",
		Subcategory:      "hats",
		Rating: ProductRating{
			Rate:  3.6,
			Count: 145,
		},
	},
	{
		ID:               10,
		Title:            "Camo Down Vest",
		ShortDescription: "Vests come in various lengths, with some ending at the waist, while others extend lower, providing different styling options",
		Description:      "The defining feature of a vest is its tailored and structured design. It boasts a front opening with buttons or snaps, a V-neck or scoop neckline, and a close fit to the body, often featuring darts or seams to ensure a sleek and flattering silhouette. Vests come in various lengths, with some ending at the waist, while others extend lower, providing different styling options. Vests are available in a wide range of fabrics and materials, from classic wool and tweed for a formal and traditional look to lightweight cotton or linen for a more relaxed and breathable feel. This versatility in materials allows vests to be worn throughout the year, adapting to both warm and cold weather. In addition to its adaptability, the vest offers a canvas for personal style expression. It can be accessorized with pocket watches, tie bars, or boutonnieres, further enhancing its visual appeal and making it an ideal choice for those who appreciate sartorial details.",
		Price:            15.99,
		Image:            "https://i.ibb.co/xJS0T3Y/camo-vest.png",
		DateAdded:        "1691220343000",
		Category:         "men",
		Subcategory:      "shirts",
		Rating: ProductRating{
			Rate:  2.1,
			Count: 430,
		},
	},
	{
		ID:               11,
		Price:            8.99,
		Title:            "Floral T-shirt",
		ShortDescription: "Crafted from soft, breathable materials like cotton or jersey fabric, ensuring comfort even during the warmest days",
		Description:      "T-shirts are not just a style choice; they are a reflection of personality and taste. Whether you opt for a vintage band tee to showcase your musical appreciation, a crisp white tee for a timeless look, or a bold, colorful design to make a statement, the t-shirt embodies individuality and versatility. T-shirts are commonly crafted from soft, breathable materials like cotton or jersey fabric, ensuring comfort even during the warmest days. This versatility in materials also means that t-shirts come in a wide range of colors and patterns, catering to various style preferences. Its construction allows for ease of movement and comfort, making it a go-to choice for everyday wear.",
		Image:            "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
		DateAdded:        "1691220343000",
		Category:         "men",
		Subcategory:      "shirts",
		Rating: ProductRating{
			Rate:  2.9,
			Count: 250,
		},
	},
	{
		ID:               12,
		Price:            11.99,
		Image:            "https://i.ibb.co/55z32tw/long-sleeve.png",
		Title:            "Black & White Longsleeve",
		ShortDescription: "Offering breathability and comfort, makes them suitable for everyday wear",
		Description:      "Crafted from a variety of fabrics, long-sleeved shirts cater to different needs and preferences. Cotton shirts offer breathability and comfort, making them suitable for everyday wear. Whether you're dressing up for a formal event, going for a business-casual look at the office, or simply looking to elevate your everyday attire, the long-sleeved shirt is a reliable choice. Its combination of comfort, sophistication, and versatility makes it a quintessential item in any fashion-conscious individual's closet, ready to adapt to the demands of any day or season.",
		DateAdded:        "1682267143000",
		Category:         "men",
		Subcategory:      "shirts",
		Rating: ProductRating{
			Rate:  4.6,
			Count: 400,
		},
	},
	{
		ID:               13,
		Title:            "Pink T-shirt",
		ShortDescription: "Crafted from soft, breathable materials like cotton or jersey fabric, ensuring comfort even during the warmest days",
		Description:      "T-shirts are not just a style choice; they are a reflection of personality and taste. Whether you opt for a vintage band tee to showcase your musical appreciation, a crisp white tee for a timeless look, or a bold, colorful design to make a statement, the t-shirt embodies individuality and versatility. T-shirts are commonly crafted from soft, breathable materials like cotton or jersey fabric, ensuring comfort even during the warmest days. This versatility in materials also means that t-shirts come in a wide range of colors and patterns, catering to various style preferences. Its construction allows for ease of movement and comfort, making it a go-to choice for everyday wear.",
		Price:            6.99,
		Image:            "https://i.ibb.co/RvwnBL8/pink-shirt.png",
		DateAdded:        "1686805663000",
		Category:         "men",
		Subcategory:      "shirts",
		Rating: ProductRating{
			Rate:  3.9,
			Count: 120,
		},
	},
	{
		ID:               14,
		Image:            "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
		Title:            "Jean Long Sleeve",
		ShortDescription: "Provides warmth and durability, ideal for cooler seasons or outdoor activities",
		Description:      "Crafted from a variety of fabrics, long-sleeved shirts cater to different needs and preferences. Provides warmth and durability, ideal for cooler seasons or outdoor activities. Whether you're dressing up for a formal event, going for a business-casual look at the office, or simply looking to elevate your everyday attire, the long-sleeved shirt is a reliable choice. Its combination of comfort, sophistication, and versatility makes it a quintessential item in any fashion-conscious individual's closet, ready to adapt to the demands of any day or season.",
		Price:            13.99,
		DateAdded:        "1682267143000",
		Category:         "men",
		Subcategory:      "shirts",
		Rating: ProductRating{
			Rate:  2.1,
			Count: 430,
		},
	},
	{
		ID:               15,
		Title:            "Burgundy T-shirt",
		ShortDescription: "Crafted from soft, breathable materials like cotton or jersey fabric, ensuring comfort even during the warmest days",
		Description:      "T-shirts are not just a style choice; they are a reflection of personality and taste. Whether you opt for a vintage band tee to showcase your musical appreciation, a crisp white tee for a timeless look, or a bold, colorful design to make a statement, the t-shirt embodies individuality and versatility. T-shirts are commonly crafted from soft, breathable materials like cotton or jersey fabric, ensuring comfort even during the warmest days. This versatility in materials also means that t-shirts come in a wide range of colors and patterns, catering to various style preferences. Its construction allows for ease of movement and comfort, making it a go-to choice for everyday wear.",
		Price:            10.99,
		Image:            "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
		DateAdded:        "1686805663000",
		Category:         "men",
		Subcategory:      "shirts",
		Rating: ProductRating{
			Rate:  3.9,
			Count: 120,
		},
	},
	{
		ID:               16,
		Price:            34.99,
		Title:            "Black Jean Shearling",
		ShortDescription: "A reliable choice for staying warm on cooler days, and its timeless appeal ensures it will never go out of style",
		Description:      "Introducing our Denim Jacket - the quintessential embodiment of enduring style and exceptional craftsmanship. This jacket is meticulously crafted from premium denim fabric, meticulously selected for its durability and comfort, ensuring it will be a cherished addition to your wardrobe for years to come. Designed with attention to detail, our Denim Jacket boasts sturdy metal buttons, reinforced stitching, and a comfortable, tailored fit that offers both mobility and a flattering silhouette. It's a reliable choice for staying warm on cooler days, and its timeless appeal ensures it will never go out of style. From its classic design to its exceptional durability, our Denim Jacket is a wardrobe essential that speaks to your enduring sense of fashion. Make a statement of timeless style and unmatched quality with this must-have piece.",
		Image:            "https://i.ibb.co/XzcwL5s/black-shearling.png",
		DateAdded:        "1695036343000",
		Category:         "men",
		Subcategory:      "jackets",
		Rating: ProductRating{
			Rate:  3.6,
			Count: 145,
		},
	},
	{
		ID:               17,
		Price:            39.99,
		Title:            "Blue Jean Jacket",
		ShortDescription: "A wardrobe essential that speaks to your enduring sense of fashion",
		Description:      "Introducing our Denim Jacket - the quintessential embodiment of enduring style and exceptional craftsmanship. This jacket is meticulously crafted from premium denim fabric, meticulously selected for its durability and comfort, ensuring it will be a cherished addition to your wardrobe for years to come. Designed with attention to detail, our Denim Jacket boasts sturdy metal buttons, reinforced stitching, and a comfortable, tailored fit that offers both mobility and a flattering silhouette. It's a reliable choice for staying warm on cooler days, and its timeless appeal ensures it will never go out of style. From its classic design to its exceptional durability, our Denim Jacket is a wardrobe essential that speaks to your enduring sense of fashion. Make a statement of timeless style and unmatched quality with this must-have piece.",
		Image:            "https://i.ibb.co/mJS6vz0/blue-jean-jacket.png",
		DateAdded:        "1682267143000",
		Category:         "men",
		Subcategory:      "jackets",
		Rating: ProductRating{
			Rate:  3.6,
			Count: 145,
		},
	},
	{
		ID:               18,
		Title:            "Grey Jean Jacket",
		ShortDescription: "Reliable choice for staying warm on cooler days, and its timeless appeal ensures it will never go out of style",
		Description:      "Introducing our Denim Jacket - the quintessential embodiment of enduring style and exceptional craftsmanship. This jacket is meticulously crafted from premium denim fabric, meticulously selected for its durability and comfort, ensuring it will be a cherished addition to your wardrobe for years to come. Designed with attention to detail, our Denim Jacket boasts sturdy metal buttons, reinforced stitching, and a comfortable, tailored fit that offers both mobility and a flattering silhouette. It's a reliable choice for staying warm on cooler days, and its timeless appeal ensures it will never go out of style. From its classic design to its exceptional durability, our Denim Jacket is a wardrobe essential that speaks to your enduring sense of fashion. Make a statement of timeless style and unmatched quality with this must-have piece.",
		Image:            "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
		Price:            39.99,
		DateAdded:        "1686846343000",
		Category:         "women",
		Subcategory:      "jackets",
		Rating: ProductRating{
			Rate:  4.5,
			Count: 146,
		},
	},
	{
		ID:               19,
		Image:            "https://i.ibb.co/s96FpdP/brown-shearling.png",
		Title:            "Brown Shearling",
		ShortDescription: "Epitome of cozy elegance and cold-weather chic. Crafted with meticulous attention to detail",
		Description:      "Shearling Jacket, the epitome of cozy elegance and cold-weather chic. Crafted with meticulous attention to detail, this jacket combines sumptuous shearling lining with a sleek outer layer to create a luxurious and warm garment that's perfect for both style-conscious individuals and those seeking superior comfort in chilly climates. The interior shearling lining envelops you in warmth and softness, making it ideal for staying toasty during the coldest months of the year. The genuine shearling not only provides exceptional insulation but also adds a touch of luxury to your look, showcasing its natural texture and warmth. On the exterior, our Shearling Jacket boasts a refined and versatile design. Its clean lines and tailored silhouette make it suitable for both casual and dressier occasions. The zipper or button closure, along with convenient pockets, ensures functionality without compromising on style. Available in a variety of colors and finishes, our Shearling Jacket allows you to express your personal style while enjoying the benefits of this timeless and practical garment.",
		Price:            46.99,
		DateAdded:        "1682267143000",
		Category:         "men",
		Subcategory:      "jackets",
		Rating: ProductRating{
			Rate:  4.7,
			Count: 500,
		},
	},
	{
		ID:               20,
		Title:            "Tan Trench",
		ShortDescription: "Dependable choice for both rainy days and chic outings. Its versatile design seamlessly transitions from casual to formal occasions",
		Description:      "Trench, a true emblem of sophistication and style. Crafted with meticulous attention to detail, this jacket embodies the timeless charm of the classic trench coat in a modern and versatile silhouette. Made from high-quality, water-resistant fabric, this jacket offers practicality along with style, making it a dependable choice for both rainy days and chic outings. Its versatile design seamlessly transitions from casual to formal occasions, providing a go-to option for all your fashion needs. Our Trench Jacket features a tailored fit with a double-breasted front adorned with elegant buttons, exuding a refined and polished look. The waist belt cinches comfortably to accentuate your figure, while the notched lapels add a touch of timeless class.",
		Image:            "https://i.ibb.co/M6hHc3F/brown-trench.png",
		Price:            22.99,
		DateAdded:        "1695036343000",
		Category:         "women",
		Subcategory:      "jackets",
		Rating: ProductRating{
			Rate:  4.4,
			Count: 230,
		},
	},
	{
		ID:               21,
		Title:            "Blue Tanktop",
		ShortDescription: "Perfect blend of comfort and style for warm-weather days",
		Description:      "Introducing our Tank Top, the perfect blend of comfort and style for warm-weather days. Crafted from soft, breathable fabric, this tank top offers a relaxed fit that keeps you cool and comfortable. Its flattering sleeveless design and rounded neckline make it a versatile addition to your wardrobe, ideal for layering or wearing on its own. With a range of colors to choose from, our Tank Top effortlessly combines everyday comfort with a touch of casual chic. Stay comfortable and stylish all day long with this essential piece.",
		Image:            "https://i.ibb.co/7CQVJNm/blue-tank.png",
		Price:            7.99,
		DateAdded:        "1676441263000",
		Category:         "women",
		Subcategory:      "all",
		Rating: ProductRating{
			Rate:  4.5,
			Count: 146,
		},
	},
	{
		ID:               22,
		Title:            "Floral Blouse",
		ShortDescription: "Crafted with exquisite attention to detail, this blouse showcases a delicate floral pattern on a backdrop of soft, flowing fabric",
		Description:      "Introducing our Elegance in Floral Blouse, a blossoming symbol of sophistication and femininity. Crafted with exquisite attention to detail, this blouse showcases a delicate floral pattern on a backdrop of soft, flowing fabric.",
		Price:            12.99,
		Image:            "https://i.ibb.co/4W2DGKm/floral-blouse.png",
		DateAdded:        "1676441263000",
		Category:         "women",
		Subcategory:      "all",
		Rating: ProductRating{
			Rate:  4.6,
			Count: 400,
		},
	},
	{
		ID:               23,
		Title:            "Floral Dress",
		ShortDescription: "Perfect choice for formal events, weddings, or memorable evenings out",
		Description:      "Elegant Floral Dress, a timeless embodiment of grace and sophistication. This exquisite dress showcases a flowing silhouette, adorned with delicate lace detailing that adds a touch of romance to any special occasion. Crafted from luxurious, high-quality materials, this dress not only offers a comfortable fit but also ensures you stand out in style. The flattering design, featuring a cinched waist and a gracefully draping skirt, complements your figure, making it the perfect choice for formal events, weddings, or memorable evenings out.",
		Image:            "https://i.ibb.co/KV18Ysr/floral-skirt.png",
		Price:            8.99,
		DateAdded:        "1682267143000",
		Category:         "women",
		Subcategory:      "all",
		Rating: ProductRating{
			Rate:  3.9,
			Count: 120,
		},
	},
	{
		ID:               24,
		Image:            "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
		Title:            "Red Dots Dress",
		ShortDescription: "Crafted from luxurious, high-quality materials, this dress not only offers a comfortable fit but also ensures you stand out in style",
		Description:      "Red Dots Dress, a timeless embodiment of grace and sophistication. This exquisite dress showcases a flowing silhouette, adorned with delicate lace detailing that adds a touch of romance to any special occasion. Crafted from luxurious, high-quality materials, this dress not only offers a comfortable fit but also ensures you stand out in style. The flattering design, featuring a cinched waist and a gracefully draping skirt, complements your figure, making it the perfect choice for formal events, weddings, or memorable evenings out.",
		Price:            11.99,
		DateAdded:        "1682267143000",
		Category:         "women",
		Subcategory:      "all",
		Rating: ProductRating{
			Rate:  3.9,
			Count: 120,
		},
	},
	{
		ID:               25,
		Image:            "https://i.ibb.co/KmSkMbH/striped-sweater.png",
		Price:            14.99,
		Title:            "Striped Sweater",
		ShortDescription: "Designed for versatility and crafted with care",
		Description:      "The epitome of warmth and style. Crafted with precision from sumptuously soft yarn, this sweater envelops you in comfort while exuding timeless elegance. Designed for versatility and crafted with care, our Striped Sweater is a must-have addition to your winter wardrobe, ensuring you stay both snug and stylish as the temperatures drop.",
		DateAdded:        "1682267143000",
		Category:         "women",
		Subcategory:      "all",
		Rating: ProductRating{
			Rate:  4.4,
			Count: 230,
		},
	},
	{
		ID:               26,
		Image:            "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
		Price:            12.99,
		Title:            "Yellow Track Suit",
		ShortDescription: "Two-piece ensemble is designed to keep you on-trend and at ease, whether you're hitting the gym, running errands, or simply lounging at home",
		Description:      "The embodiment of sporty style and all-day comfort. This two-piece ensemble is designed to keep you on-trend and at ease, whether you're hitting the gym, running errands, or simply lounging at home. Available in a range of colors to suit your personal style, our Track Suit is the perfect choice for those seeking a blend of fashion and functionality. Elevate your casual wardrobe with this versatile ensemble, designed for comfort and style wherever you go.",
		DateAdded:        "1676441263000",
		Category:         "women",
		Subcategory:      "all",
		Rating: ProductRating{
			Rate:  4.5,
			Count: 146,
		},
	},
	{
		ID:               27,
		Image:            "https://i.ibb.co/qBcrsJg/white-vest.png",
		Title:            "White Blouse",
		ShortDescription: "Introducing our elegance in White Blouse, a blossoming symbol of sophistication and femininity",
		Description:      "Introducing our elegance in White Blouse, a blossoming symbol of sophistication and femininity. Crafted with exquisite attention to detail, this blouse showcases a delicate floral pattern on a backdrop of soft, flowing fabric.",
		Price:            14.99,
		DateAdded:        "1686846343000",
		Category:         "women",
		Subcategory:      "all",
		Rating: ProductRating{
			Rate:  3.9,
			Count: 120,
		},
	},
	{
		ID:               28,
		Title:            "Adidas NMD",
		ShortDescription: "Perfect fusion of style and comfort",
		Description:      "Perfect fusion of style and comfort. These sneakers are designed to accompany you on all your adventures, from urban streets to outdoor escapades. Crafted with precision, our Adidas NMD Sneakers boast a sleek and versatile design that effortlessly complements any outfit. The premium materials ensure durability, while the cushioned insole provides all-day comfort.",
		Price:            99.99,
		Image:            "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
		DateAdded:        "1676441263000",
		Category:         "unisex",
		Subcategory:      "footwear",
		Rating: ProductRating{
			Rate:  3.3,
			Count: 203,
		},
	},
	{
		ID:               29,
		Price:            89.99,
		Image:            "https://i.ibb.co/dJbG1cT/yeezy.png",
		Title:            "Adidas Yeezy",
		ShortDescription: "Designed to accompany you on all your adventures",
		Description:      "Perfect fusion of style and comfort. These sneakers are designed to accompany you on all your adventures, from urban streets to outdoor escapades. Crafted with precision, our Adidas Yeezy Sneakers boast a sleek and versatile design that effortlessly complements any outfit. The premium materials ensure durability, while the cushioned insole provides all-day comfort.",
		DateAdded:        "1682267143000",
		Category:         "unisex",
		Subcategory:      "footwear",
		Rating: ProductRating{
			Rate:  4.8,
			Count: 400,
		},
	},
	{
		ID:               30,
		Title:            "Black Converse",
		ShortDescription: "Crafted with precision",
		Description:      "Perfect fusion of style and comfort. These sneakers are designed to accompany you on all your adventures, from urban streets to outdoor escapades. Crafted with precision, Black Converse Sneakers boast a sleek and versatile design that effortlessly complements any outfit. The premium materials ensure durability, while the cushioned insole provides all-day comfort.",
		Price:            39.99,
		Image:            "https://i.ibb.co/bPmVXyP/black-converse.png",
		DateAdded:        "1682267143000",
		Category:         "unisex",
		Subcategory:      "footwear",
		Rating: ProductRating{
			Rate:  4.6,
			Count: 400,
		},
	},
	{
		ID:               31,
		Price:            69.99,
		Title:            "Nike White AirForce",
		ShortDescription: "Premium materials ensure durability, while the cushioned insole provides all-day comfort",
		Description:      "Perfect fusion of style and comfort. These sneakers are designed to accompany you on all your adventures, from urban streets to outdoor escapades. Crafted with precision, Nike AirForce Sneakers boast a sleek and versatile design that effortlessly complements any outfit. The premium materials ensure durability, while the cushioned insole provides all-day comfort.",
		Image:            "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
		DateAdded:        "1686846343000",
		Category:         "unisex",
		Subcategory:      "footwear",
		Rating: ProductRating{
			Rate:  3.9,
			Count: 120,
		},
	},
	{
		ID:               32,
		Price:            59.99,
		Title:            "Nike Red High Tops",
		ShortDescription: "Design that effortlessly complements any outfit",
		Description:      "Perfect fusion of style and comfort. These sneakers are designed to accompany you on all your adventures, from urban streets to outdoor escapades. Crafted with precision, Nike High Tops boast a sleek and versatile design that effortlessly complements any outfit. The premium materials ensure durability, while the cushioned insole provides all-day comfort.",
		Image:            "https://i.ibb.co/QcvzydB/nikes-red.png",
		DateAdded:        "1686846343000",
		Category:         "unisex",
		Subcategory:      "footwear",
		Rating: ProductRating{
			Rate:  3.9,
			Count: 120,
		},
	},
	{
		ID:               33,
		Price:            44.99,
		Image:            "https://i.ibb.co/fMTV342/nike-brown.png",
		Title:            "Nike Brown High Tops",
		ShortDescription: "Sneakers are designed to accompany you on all your adventures, from urban streets to outdoor escapades",
		Description:      "Perfect fusion of style and comfort. These sneakers are designed to accompany you on all your adventures, from urban streets to outdoor escapades. Crafted with precision, Nike High Tops boast a sleek and versatile design that effortlessly complements any outfit. The premium materials ensure durability, while the cushioned insole provides all-day comfort.",
		DateAdded:        "1686846343000",
		Category:         "unisex",
		Subcategory:      "footwear",
		Rating: ProductRating{
			Rate:  4.6,
			Count: 400,
		},
	},
	{
		ID:               34,
		Title:            "Air Jordan Limited",
		ShortDescription: "Materials ensure durability and perfect fusion of style and comfort",
		Description:      "Perfect fusion of style and comfort. These sneakers are designed to accompany you on all your adventures, from urban streets to outdoor escapades. Crafted with precision, Air Jordan Limited boast a sleek and versatile design that effortlessly complements any outfit. The premium materials ensure durability, while the cushioned insole provides all-day comfort.",
		Image:            "https://i.ibb.co/w4k6Ws9/nike-funky.png",
		Price:            149.99,
		DateAdded:        "1676441263000",
		Category:         "unisex",
		Subcategory:      "footwear",
		Rating: ProductRating{
			Rate:  4.7,
			Count: 500,
		},
	},
	{
		ID:               35,
		Image:            "https://i.ibb.co/Mhh6wBg/timberlands.png",
		Price:            99.99,
		Title:            "Timberlands",
		ShortDescription: "Embrace the spirit of exploration and elevate your footwear game with Timberland",
		Description:      "Introducing our Timberland Boots - where rugged durability meets timeless style. Crafted to withstand the toughest conditions, these iconic boots are the epitome of outdoor adventure and urban cool. Built with premium materials and a signature waterproof design, Timberland Boots keep you comfortable and dry, no matter the weather. The iconic yellow laces and logo details add a touch of authenticity to your look, making these boots the perfect blend of fashion and function. From hiking trails to city streets, Timberland Boots are your trusty companions, offering unbeatable comfort and a classic aesthetic that never goes out of style. Embrace the spirit of exploration and elevate your footwear game with Timberland.",
		DateAdded:        "1691220343000",
		Category:         "unisex",
		Subcategory:      "footwear",
		Rating: ProductRating{
			Rate:  4.7,
			Count: 500,
		},
	},
}
